/*
-- Query: SELECT * FROM estate_ads.ads_district
LIMIT 0, 1000

-- Date: 2015-01-21 13:28
*/
INSERT INTO `ads_district` (`id`,`town_id`,`name_ru`,`name_en`,`name_uk`) VALUES (1,1,'Дзержинский','Dzerzhinsky','Дзержинський');
INSERT INTO `ads_district` (`id`,`town_id`,`name_ru`,`name_en`,`name_uk`) VALUES (2,1,'Киевский','Kyivskiy','Київський');
INSERT INTO `ads_district` (`id`,`town_id`,`name_ru`,`name_en`,`name_uk`) VALUES (3,1,'Коминтерновский','Kominternovskiy','Комінтернівський');
INSERT INTO `ads_district` (`id`,`town_id`,`name_ru`,`name_en`,`name_uk`) VALUES (4,1,'Алексеевский','Alekseyevskiy','Олексіївський');
INSERT INTO `ads_district` (`id`,`town_id`,`name_ru`,`name_en`,`name_uk`) VALUES (86,1,'Большая Даниловка','Большая Даниловка','Большая Даниловка');
INSERT INTO `ads_district` (`id`,`town_id`,`name_ru`,`name_en`,`name_uk`) VALUES (87,1,'Богодуховский р-н','Богодуховский р-н','Богодуховский р-н');
INSERT INTO `ads_district` (`id`,`town_id`,`name_ru`,`name_en`,`name_uk`) VALUES (88,1,'Конный рынок','Конный рынок','Конный рынок');
INSERT INTO `ads_district` (`id`,`town_id`,`name_ru`,`name_en`,`name_uk`) VALUES (89,1,'Шишковка','Шишковка','Шишковка');
INSERT INTO `ads_district` (`id`,`town_id`,`name_ru`,`name_en`,`name_uk`) VALUES (90,1,'Залютино поселок','Залютино поселок','Залютино поселок');
INSERT INTO `ads_district` (`id`,`town_id`,`name_ru`,`name_en`,`name_uk`) VALUES (91,1,'Чугуевский р-н','Чугуевский р-н','Чугуевский р-н');
INSERT INTO `ads_district` (`id`,`town_id`,`name_ru`,`name_en`,`name_uk`) VALUES (92,1,'Герцена поселок','Герцена поселок','Герцена поселок');
INSERT INTO `ads_district` (`id`,`town_id`,`name_ru`,`name_en`,`name_uk`) VALUES (93,1,'Липовая Роща','Липовая Роща','Липовая Роща');
INSERT INTO `ads_district` (`id`,`town_id`,`name_ru`,`name_en`,`name_uk`) VALUES (94,1,'Руднева площадь','Руднева площадь','Руднева площадь');
INSERT INTO `ads_district` (`id`,`town_id`,`name_ru`,`name_en`,`name_uk`) VALUES (95,1,'Пески','Пески','Пески');
INSERT INTO `ads_district` (`id`,`town_id`,`name_ru`,`name_en`,`name_uk`) VALUES (96,1,'Золочевский р-н','Золочевский р-н','Золочевский р-н');
INSERT INTO `ads_district` (`id`,`town_id`,`name_ru`,`name_en`,`name_uk`) VALUES (97,1,'Алексеевка','Алексеевка','Алексеевка');
INSERT INTO `ads_district` (`id`,`town_id`,`name_ru`,`name_en`,`name_uk`) VALUES (98,1,'Сортировка','Сортировка','Сортировка');
INSERT INTO `ads_district` (`id`,`town_id`,`name_ru`,`name_en`,`name_uk`) VALUES (99,1,'Госпром','Госпром','Госпром');
INSERT INTO `ads_district` (`id`,`town_id`,`name_ru`,`name_en`,`name_uk`) VALUES (100,1,'Волчанский р-н','Волчанский р-н','Волчанский р-н');
INSERT INTO `ads_district` (`id`,`town_id`,`name_ru`,`name_en`,`name_uk`) VALUES (101,1,'Балаклейский р-н','Балаклейский р-н','Балаклейский р-н');
INSERT INTO `ads_district` (`id`,`town_id`,`name_ru`,`name_en`,`name_uk`) VALUES (102,1,'Павлово Поле','Павлово Поле','Павлово Поле');
INSERT INTO `ads_district` (`id`,`town_id`,`name_ru`,`name_en`,`name_uk`) VALUES (103,1,'Одесская','Одесская','Одесская');
INSERT INTO `ads_district` (`id`,`town_id`,`name_ru`,`name_en`,`name_uk`) VALUES (104,1,'Бавария','Бавария','Бавария');
INSERT INTO `ads_district` (`id`,`town_id`,`name_ru`,`name_en`,`name_uk`) VALUES (105,1,'Петренки','Петренки','Петренки');
INSERT INTO `ads_district` (`id`,`town_id`,`name_ru`,`name_en`,`name_uk`) VALUES (106,1,'Окружная дорога','Окружная дорога','Окружная дорога');
INSERT INTO `ads_district` (`id`,`town_id`,`name_ru`,`name_en`,`name_uk`) VALUES (107,1,'Красный луч','Красный луч','Красный луч');
INSERT INTO `ads_district` (`id`,`town_id`,`name_ru`,`name_en`,`name_uk`) VALUES (108,1,'Хроли','Хроли','Хроли');
INSERT INTO `ads_district` (`id`,`town_id`,`name_ru`,`name_en`,`name_uk`) VALUES (109,1,'м.Масельского','м.Масельского','м.Масельского');
INSERT INTO `ads_district` (`id`,`town_id`,`name_ru`,`name_en`,`name_uk`) VALUES (110,1,'Восточный поселок ','Восточный поселок ','Восточный поселок ');
INSERT INTO `ads_district` (`id`,`town_id`,`name_ru`,`name_en`,`name_uk`) VALUES (111,1,'Ивановка','Ивановка','Ивановка');
INSERT INTO `ads_district` (`id`,`town_id`,`name_ru`,`name_en`,`name_uk`) VALUES (112,1,'Сабурова дача','Сабурова дача','Сабурова дача');
INSERT INTO `ads_district` (`id`,`town_id`,`name_ru`,`name_en`,`name_uk`) VALUES (113,1,'Змиевской р-н','Змиевской р-н','Змиевской р-н');
INSERT INTO `ads_district` (`id`,`town_id`,`name_ru`,`name_en`,`name_uk`) VALUES (114,1,'Нововодолажский р-н','Нововодолажский р-н','Нововодолажский р-н');
INSERT INTO `ads_district` (`id`,`town_id`,`name_ru`,`name_en`,`name_uk`) VALUES (115,1,'Первомайский р-н','Первомайский р-н','Первомайский р-н');
INSERT INTO `ads_district` (`id`,`town_id`,`name_ru`,`name_en`,`name_uk`) VALUES (116,1,'Шатилова дача','Шатилова дача','Шатилова дача');
INSERT INTO `ads_district` (`id`,`town_id`,`name_ru`,`name_en`,`name_uk`) VALUES (117,1,'Изюмский р-н','Изюмский р-н','Изюмский р-н');
INSERT INTO `ads_district` (`id`,`town_id`,`name_ru`,`name_en`,`name_uk`) VALUES (118,1,'Верещаковка','Верещаковка','Верещаковка');
INSERT INTO `ads_district` (`id`,`town_id`,`name_ru`,`name_en`,`name_uk`) VALUES (119,1,'Филипповка','Филипповка','Филипповка');
INSERT INTO `ads_district` (`id`,`town_id`,`name_ru`,`name_en`,`name_uk`) VALUES (120,1,'Лозовской р-н','Лозовской р-н','Лозовской р-н');
INSERT INTO `ads_district` (`id`,`town_id`,`name_ru`,`name_en`,`name_uk`) VALUES (121,1,'Балашовка','Балашовка','Балашовка');
INSERT INTO `ads_district` (`id`,`town_id`,`name_ru`,`name_en`,`name_uk`) VALUES (122,1,'Нагорный','Нагорный','Нагорный');
INSERT INTO `ads_district` (`id`,`town_id`,`name_ru`,`name_en`,`name_uk`) VALUES (123,1,'Салтовка','Салтовка','Салтовка');
INSERT INTO `ads_district` (`id`,`town_id`,`name_ru`,`name_en`,`name_uk`) VALUES (124,1,'Двуречанский р-н','Двуречанский р-н','Двуречанский р-н');
INSERT INTO `ads_district` (`id`,`town_id`,`name_ru`,`name_en`,`name_uk`) VALUES (125,1,'Гагарина','Гагарина','Гагарина');
INSERT INTO `ads_district` (`id`,`town_id`,`name_ru`,`name_en`,`name_uk`) VALUES (126,1,'Краснокутский р-н','Краснокутский р-н','Краснокутский р-н');
INSERT INTO `ads_district` (`id`,`town_id`,`name_ru`,`name_en`,`name_uk`) VALUES (127,1,'Роганский ж/м','Роганский ж/м','Роганский ж/м');
INSERT INTO `ads_district` (`id`,`town_id`,`name_ru`,`name_en`,`name_uk`) VALUES (128,1,'Котлова ул.','Котлова ул.','Котлова ул.');
INSERT INTO `ads_district` (`id`,`town_id`,`name_ru`,`name_en`,`name_uk`) VALUES (129,1,'Дергачевский р-н','Дергачевский р-н','Дергачевский р-н');
INSERT INTO `ads_district` (`id`,`town_id`,`name_ru`,`name_en`,`name_uk`) VALUES (130,1,'Жуковского поселок','Жуковского поселок','Жуковского поселок');
INSERT INTO `ads_district` (`id`,`town_id`,`name_ru`,`name_en`,`name_uk`) VALUES (131,1,'Немышля','Немышля','Немышля');
INSERT INTO `ads_district` (`id`,`town_id`,`name_ru`,`name_en`,`name_uk`) VALUES (132,1,'Новоселовка','Новоселовка','Новоселовка');
INSERT INTO `ads_district` (`id`,`town_id`,`name_ru`,`name_en`,`name_uk`) VALUES (133,1,'Харьковский р-н','Харьковский р-н','Харьковский р-н');
INSERT INTO `ads_district` (`id`,`town_id`,`name_ru`,`name_en`,`name_uk`) VALUES (134,1,'Малая Даниловка','Малая Даниловка','Малая Даниловка');
INSERT INTO `ads_district` (`id`,`town_id`,`name_ru`,`name_en`,`name_uk`) VALUES (135,1,'Артема поселок','Артема поселок','Артема поселок');
INSERT INTO `ads_district` (`id`,`town_id`,`name_ru`,`name_en`,`name_uk`) VALUES (136,1,'Новожанова','Новожанова','Новожанова');
INSERT INTO `ads_district` (`id`,`town_id`,`name_ru`,`name_en`,`name_uk`) VALUES (137,1,'Печенежский р-н','Печенежский р-н','Печенежский р-н');
INSERT INTO `ads_district` (`id`,`town_id`,`name_ru`,`name_en`,`name_uk`) VALUES (138,1,'Валковский р-н','Валковский р-н','Валковский р-н');
INSERT INTO `ads_district` (`id`,`town_id`,`name_ru`,`name_en`,`name_uk`) VALUES (139,1,'пригород','пригород','пригород');
INSERT INTO `ads_district` (`id`,`town_id`,`name_ru`,`name_en`,`name_uk`) VALUES (140,1,'Новые Дома','Новые Дома','Новые Дома');
INSERT INTO `ads_district` (`id`,`town_id`,`name_ru`,`name_en`,`name_uk`) VALUES (141,1,'Новый Цирк','Новый Цирк','Новый Цирк');
INSERT INTO `ads_district` (`id`,`town_id`,`name_ru`,`name_en`,`name_uk`) VALUES (142,1,'Московский проспект','Московский проспект','Московский проспект');
INSERT INTO `ads_district` (`id`,`town_id`,`name_ru`,`name_en`,`name_uk`) VALUES (143,1,'Пятихатки поселок','Пятихатки поселок','Пятихатки поселок');
INSERT INTO `ads_district` (`id`,`town_id`,`name_ru`,`name_en`,`name_uk`) VALUES (144,1,'Павловка','Павловка','Павловка');
INSERT INTO `ads_district` (`id`,`town_id`,`name_ru`,`name_en`,`name_uk`) VALUES (145,1,'Южный вокзал','Южный вокзал','Южный вокзал');
INSERT INTO `ads_district` (`id`,`town_id`,`name_ru`,`name_en`,`name_uk`) VALUES (146,1,'Аэропорт','Аэропорт','Аэропорт');
INSERT INTO `ads_district` (`id`,`town_id`,`name_ru`,`name_en`,`name_uk`) VALUES (147,1,'Гидропарк','Гидропарк','Гидропарк');
INSERT INTO `ads_district` (`id`,`town_id`,`name_ru`,`name_en`,`name_uk`) VALUES (148,1,'Песочин поселок','Песочин поселок','Песочин поселок');
INSERT INTO `ads_district` (`id`,`town_id`,`name_ru`,`name_en`,`name_uk`) VALUES (149,1,'Основа','Основа','Основа');
INSERT INTO `ads_district` (`id`,`town_id`,`name_ru`,`name_en`,`name_uk`) VALUES (150,1,'Украина','Украина','Украина');
INSERT INTO `ads_district` (`id`,`town_id`,`name_ru`,`name_en`,`name_uk`) VALUES (151,1,'Лесопарк','Лесопарк','Лесопарк');
INSERT INTO `ads_district` (`id`,`town_id`,`name_ru`,`name_en`,`name_uk`) VALUES (152,1,'Кегичевский р-н','Кегичевский р-н','Кегичевский р-н');
INSERT INTO `ads_district` (`id`,`town_id`,`name_ru`,`name_en`,`name_uk`) VALUES (153,1,'Холодная Гора','Холодная Гора','Холодная Гора');
INSERT INTO `ads_district` (`id`,`town_id`,`name_ru`,`name_en`,`name_uk`) VALUES (154,1,'Центр','Центр','Центр');
INSERT INTO `ads_district` (`id`,`town_id`,`name_ru`,`name_en`,`name_uk`) VALUES (155,1,'Лысая гора','Лысая гора','Лысая гора');
INSERT INTO `ads_district` (`id`,`town_id`,`name_ru`,`name_en`,`name_uk`) VALUES (156,1,'Сосновая Горка','Сосновая Горка','Сосновая Горка');
INSERT INTO `ads_district` (`id`,`town_id`,`name_ru`,`name_en`,`name_uk`) VALUES (157,1,'м. Научная','м. Научная','м. Научная');
INSERT INTO `ads_district` (`id`,`town_id`,`name_ru`,`name_en`,`name_uk`) VALUES (158,1,'ХТЗ','ХТЗ','ХТЗ');
INSERT INTO `ads_district` (`id`,`town_id`,`name_ru`,`name_en`,`name_uk`) VALUES (159,1,'Ленинский район','Ленинский район','Ленинский район');
INSERT INTO `ads_district` (`id`,`town_id`,`name_ru`,`name_en`,`name_uk`) VALUES (160,1,'Солнечный м-рн','Солнечный м-рн','Солнечный м-рн');
INSERT INTO `ads_district` (`id`,`town_id`,`name_ru`,`name_en`,`name_uk`) VALUES (161,1,'Москалевка','Москалевка','Москалевка');
INSERT INTO `ads_district` (`id`,`town_id`,`name_ru`,`name_en`,`name_uk`) VALUES (162,1,'Северная Салтовка','Северная Салтовка','Северная Салтовка');
INSERT INTO `ads_district` (`id`,`town_id`,`name_ru`,`name_en`,`name_uk`) VALUES (163,1,'Красноградский р-н','Красноградский р-н','Красноградский р-н');
INSERT INTO `ads_district` (`id`,`town_id`,`name_ru`,`name_en`,`name_uk`) VALUES (164,1,'Журавлевка','Журавлевка','Журавлевка');
INSERT INTO `ads_district` (`id`,`town_id`,`name_ru`,`name_en`,`name_uk`) VALUES (165,1,'Горизонт ','Горизонт ','Горизонт ');
INSERT INTO `ads_district` (`id`,`town_id`,`name_ru`,`name_en`,`name_uk`) VALUES (166,1,'Купянский р-н','Купянский р-н','Купянский р-н');
